### ISSUE TITLE
Toolbar Unavailable

### ISSUE THREAD

**Issue by bkuri** [destroytoday/Dwarf#3]
Clicking on the system tray icon will seldom open up the Dwarf toolbar. Clicking on it repeatedly sometimes forces it to open, however.

This may just be a Linux+AIR issue, but I can't be sure until I test this under Windows.

**Comment by destroytoday** [comment]
Test the next build that will be posted tonight.

**Comment by bkuri** [comment]
The latest version is much improved in this regard, although Linux still causes it to stay hidden if a change to another viewport (this could apply to OSX as well, but I'm not sure).

To reproduce this, one just needs to open Dwarf in one viewport, and then switch to another viewport and attempt to get the bar to open up.

The bigger issue here is that the bar will almost never reappear, even if I return to the original viewport.
