### ISSUE TITLE
Additional Toolbar Display Issues

### ISSUE THREAD

**Issue by bkuri** [destroytoday/Dwarf#4]
Using multiple displays, the toolbar sometimes shows up on the wrong monitor, but with the width of the first monitor.

Additionally, the toolbar will trigger a viewport change when I click on the tray icon (as opposed to just showing itself in the active viewport).

**Comment by bkuri** [comment]
P.S. Again, this could be an issue with Linux+AIR, but I have no way of verifying that at the moment.

**Comment by destroytoday** [comment]
I added a fix to resize the toolbar upon invoke (clicking the system tray icon). It will always appear on the screen considered the 'mainScreen'. Test in the next build.
