### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by bkuri** [destroytoday/Dwarf#7]
Steps to reproduce:
1. Click on the "New Ruler" button on the toolbar
2. Click on "New Guide"

Instead of the button getting clicked, the first ruler gets a "MouseDown" event and starts moving with the mouse (even if the pointer is outside it's boundaries, exactly as if I was trying to move the ruler in the first place).

The only way to be able to interact with Dwarf again (to add more items, click on buttons, etc) is to right click on the ruler and force the context menu to appear. After that I can click on any item individually again.

Hope that made sense!

**Comment by destroytoday** [comment]
Doesn't occur on Mac—might be an AIR/Linux bug.
