### ISSUE TITLE
Issues with Guides

### ISSUE THREAD

**Issue by bkuri** [destroytoday/Dwarf#8]
I found a number of issues with these:
1. I can't drag a horizontal guide to my other (non-active) monitor.
2. I can't create a horizontal guide that spans the width of both monitors.
3. Cutting (Crtrl+X) a guide works, pasting (Ctrl+V) rarely does paste a guide, and when it does, it doesn't restore it's X,Y properties

**Comment by destroytoday** [comment]
Regarding #3, can you provide clipboard data when a guide doesn't paste? It uses a regex to verify the clipboard data, so I'm wondering if there's a case I'm not accounting for.

**Comment by bkuri** [comment]
Here's some output for a guide:

type=Guide x=0 y=670 width=1400 height=11 color=31128 alpha=0.2 orientation=horizontal

**Comment by bkuri** [comment]
The following guide changed from horizontal on monitor #1 to vertical on monitor #2 (no mouse movement whatsoever):

type=Guide x=0 y=525 width=1400 height=11 color=31128 alpha=0.2 orientation=horizontal

I'm not sure if this is enough information to clear this up though... Would you like me to try something else?

**Comment by bkuri** [comment]
Another issue that I'm encountering is that pasting sometimes replaces my previous guide, instead of appending a new one...

**Comment by destroytoday** [comment]
I tested these on Mac and I don't experience the issue. It might be an AIR/Linux thing. I'll have to try it out.

**Comment by destroytoday** [comment]
Regarding #1, I plan to allow switching guides' screens by command/control-dragging. Because there's the guide dragging bug in Linux (drags freely instead of on an axis), you won't have to hold control.

Regarding #2, guides are screen-specific and shouldn't span across multiple.
