### ISSUE TITLE
[Suggestion] Snap to center and edges

### ISSUE THREAD

**Issue by bkuri** [destroytoday/Dwarf#9]
It would be really handy to be able to snap guides to the (horizontal/vertical) center of the screen and borders whenever I'm dragging the guide towards said area (just like in Photoshop). I think only a slight "resistance" would be enough, rather than actually removing the mouse capture.

**Comment by destroytoday** [comment]
On Mac, if I'm in Photoshop, I can prompt the hand cursor and click/drag the image within a window by holding the command key when dragging. What's the equivalent in Windows/Linux? Is it alt?

**Comment by bkuri** [comment]
I believe the Command key in Mac is the same as the Control key in PCs.
